version: "3.9"
services:
  nginx:
    container_name: nginx
    image: nginx

  grafana:
    container_name: grafana
    image: grafana/grafana
    environment:
      GF_SECURITY_ADMIN_USER: admin
      GF_SECURITY_ADMIN_PASSWORD: admin

  mitm:
    container_name: mitm
    image: mitmproxy/mitmproxy

  alpine:
    container_name: alpine
    image: alpine
    command: "sleep 5h"
