version: "3.9"
services:
  nginx:
    container_name: nginx
    image: nginx
    ports:
      - "8080:80"

  grafana:
    container_name: grafana
    image: grafana/grafana
    ports:
      - "3000:3000"

  alpine:
    container_name: alpine
    image: alpine-custom
    build:
      context: .
    command: "custom.txt"
