version: "3.9"
services:
  pgadmin:
    image: dpage/pgadmin4
    ports:
      - "8080:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: "admin@admin.com"
      PGADMIN_DEFAULT_PASSWORD: "admin"
    networks:
      - web
  postgres:
    image: postgres:13
    environment:
      POSTGRES_HOST_AUTH_METHOD: password
      POSTGRES_PASSWORD: "postgres"
    networks:
      - db

networks:
  web:
    name: custom-web-network
  db:
    name: custom-db-network